import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from "react-bootstrap";
import "@fontsource/inter";
import "@fontsource/inter/400.css";
import "@fontsource/inter/400-italic.css"; 
import Header from "./components/Common/Header";

import Footer from "./components/Common/Footer";
import "./globals.css"
import "./responsive.css"


export const metadata = {
  title: "Checkvalet",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
      
       
        {children}
     <Footer/>
       
      </body>
    </html>
  );
}
